name = "HHServer 5.0"
author = "claw"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cf3e921614d2463231544552b75531f09d097b02beb7b6fd28e84ddbe37c334"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
